### ISSUE TITLE
try to execute titlemantle both on Windows and Mac... I receive this error:

### ISSUE THREAD

**Issue by dariocavada** [naturalatlas/tilemantle#2]
try to execute titlemantle both on Windows and Mac... I receive this error:

module.js:340
    throw err;
          ^
Error: Cannot find module '../bower_components/closure-library/closure/goog/bootstrap/nodejs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Users\dario\AppData\Roaming\npm\node_modules\tilemantle\node_modules\turf\node_modules\turf-union\node_modules\jsts\node_modules\j
avascript.util\dist\javascript.util-node.min.js:42:237)
    at Object.<anonymous> (C:\Users\dario\AppData\Roaming\npm\node_modules\tilemantle\node_modules\turf\node_modules\turf-union\node_modules\jsts\node_modules\j
avascript.util\dist\javascript.util-node.min.js:42:339)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by brianreavis** [comment]
Unfortunately this is caused by breaking changes on an upstream module (cc @bjornharrtell):
https://github.com/bjornharrtell/javascript.util/issues/10
https://github.com/bjornharrtell/jsts/pull/174

**Comment by bjornharrtell** [comment]
Sorry to hear that, is it still broken as of version 0.12.11?

**Comment by bjornharrtell** [comment]
I see that this project depends on an old version of turf.js, if upgraded to 2.0.2 there should be no issues.

**Comment by brianreavis** [comment]
Thanks @bjornharrtell, looks like that did it. @dariocavada Do you mind giving [1.0.3](https://github.com/naturalatlas/tilemantle/releases/tag/v1.0.3) a shot?
