### ISSUE TITLE
Unable to generate map tiles

### ISSUE THREAD

**Issue by mfeuermann** [naturalatlas/tilemantle#3]
Hello 

i have problem with command

tilemantle http://IP:8080/pluto/{z}/{x}/{y}/tile.png --extent=12.09,51.06,18.87,48.55 --zoom=8-10

/usr/local/lib/node_modules/tilemantle/node_modules/turf/node_modules/turf-merge/index.js:55
  var merged = clone(polygons.features[0]),
                                      ^
TypeError: Cannot read property '0' of undefined
    at Object.module.exports [as merge](/usr/local/lib/node_modules/tilemantle/node_modules/turf/node_modules/turf-merge/index.js:55:39)
    at determineGeometry (/usr/local/lib/node_modules/tilemantle/bin/tilemantle.js:128:18)
    at /usr/local/lib/node_modules/tilemantle/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/tilemantle/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/tilemantle/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/tilemantle/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/tilemantle/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/tilemantle/node_modules/async/lib/async.js:615:34
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/tilemantle/bin/tilemantle.js:91:5)
    at ReadStream.EventEmitter.emit (events.js:92:17)

Can you help me with this problem ?
Thank you
Marek

**Comment by brianreavis** [comment]
Can you [gist](https://gist.github.com/) the geometry you're passing to it?

**Comment by thebabelfish** [comment]
Hello,

I have encountered the exact same issue as above but additionally using geojson as a source.

I have tried the following formats (in files) using cat region.geojson | tilemantle http://myhost.com/{z}/{x}/{y}.png -z 10-14

```{
  "type": "Feature",
  "geometry": {"type":"MultiPolygon","coordinates":[[[-18.3936862946,27.4335422516],[-18.3936862946,43.993309021],[4.5918889046,43.993309021],[-18.3936862946,27.4335422516],[-18.3936862946,27.4335422516]]]
  }
}```

-----

 {"type":"MultiPolygon","coordinates":[[[-18.3936862946,27.4335422516],[-18.3936862946,43.993309021],[4.5918889046,43.993309021],[-18.3936862946,27.4335422516],[-18.3936862946,27.4335422516]]]
  }

----

```
[[[-18.3936862946,27.4335422516],[-18.3936862946,43.993309021],[4.5918889046,43.993309021],[-18.3936862946,27.4335422516],[-18.3936862946,27.4335422516]]]
```



I am running node v0.12.7 with tilemantle 1.2.0.

Any insight is greatly appreciated
